### generate only lotResults
GET {{host}}/{{generator}}/lot-result
Content-Type: application/json

### generate lotResults and lotPDFResults with laptopItems for those lotResults who have the status PDF_SUCCESSFULL
GET {{host}}/{{generator}}/lot-pdf-result
Content-Type: application/json

### generate laptopItems for one already exist lotPDFResult
GET {{host}}/{{generator}}/laptop-item/{{lotPDFResult}}

### receive all lots from prozorro api
GET {{host}}/api_lot_extract_all
Content-Type: application/json

### receive one lot from prozorro api
GET {{host}}//:lotId
//lotId=b03c713a16a34d3c94cce7010d9081a4
Content-Type: application/json